import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { apply } from '../src/index.js';
import { Store } from '../src/storage.js';
import { defaultConfig } from '../src/contracts.js';
import { defaultTables } from '../src/defaults.js';

test('Conversation settings survive card selection and remain separate from later global defaults', async t => {
  const root = await mkdtemp(join(tmpdir(), 'tavern-settings-')), disposers = [];
  let handler;
  const sessions = new Map(['first', 'next'].map(id => [id, { id, header: {}, snapshotEvents: () => [] }]));
  const ctx = { sessions, agents: new Map(), llm: {}, connection: { requestRejection: () => null }, sessionProjections: { stateOf: () => 'tavern' }, reflect: { provide(name, value) { ctx[name] = value; } }, on() {}, effect(fn) { const dispose = fn(); if (typeof dispose === 'function') disposers.push(dispose); }, webServer: { register(options) { handler = options.handler; return () => {}; }, registerUpgrade: () => () => {} } };
  t.after(async () => { for (const dispose of disposers.toReversed()) await dispose(); await rm(root, { recursive: true, force: true }); });
  await apply(ctx, { dataDir: root });
  const store = new Store(root);
  const preset = content => ({ prompts: [{ identifier: 'main', name: '主提示词', role: 'system', content }], prompt_order: [{ character_id: 100001, order: [{ identifier: 'main', enabled: true }] }] });
  await store.putItem({ id: 'card', kind: 'card', name: '图书馆', data: { name: '图书馆', first_mes: '开门了。' } });
  await store.putItem({ id: 'preset', kind: 'preset', name: '参观预设', data: preset('原始提示词') });
  await store.putItem({ id: 'tables', kind: 'tables', name: '默认表格', data: defaultTables() });
  const defaults = { selection: { presetId: 'preset', tableId: 'tables', userName: '访客' }, config: defaultConfig() };
  await store.saveSettings(defaults);
  async function call(path, value) {
    let body;
    const req = { method: value === undefined ? 'GET' : 'POST', url: '/api/tavern' + path, async *[Symbol.asyncIterator]() { yield Buffer.from(JSON.stringify(value)); } };
    const res = { writeHead(status) { this.status = status; }, end(text) { body = JSON.parse(text); } };
    await handler(req, res); assert.equal(res.status, 200, body.error); return body;
  }
  const first = await call('/native-ensure', { id: 'first' });
  assert.equal(first.state, null); assert.equal(first.selection.userName, '访客');
  assert.equal(first.selection.tableId, 'tables');
  await call('/native-selection', { id: 'first', selection: { presetId: 'preset', userName: '本对话访客', renderMode: 'card' } });
  const localConfig = { ...defaultConfig(), historyTurns: 5 };
  await call('/config', { sessionId: 'first', config: localConfig });
  await call('/item', { sessionId: 'first', id: 'preset', data: preset('本对话提示词') });
  assert.deepEqual((await store.item('preset')).data, preset('本对话提示词'));
  assert.deepEqual((await store.settings()).selection, defaults.selection);
  const config = { ...defaultConfig(), historyTurns: 9 };
  await call('/config', { config });
  await call('/native-selection', { selection: { presetId: 'preset', userName: '新对话访客' } });
  await call('/item', { scope: 'global', id: 'preset', data: preset('全局默认提示词') });
  assert.deepEqual((await store.item('preset')).data, preset('全局默认提示词'));
  let saved = await call('/native-selection', { id: 'first', selection: { cardId: 'card' } });
  assert.equal(saved.state.userName, '本对话访客'); assert.equal(saved.state.config.historyTurns, 5);
  assert.equal(saved.state.tableId, 'tables');
  assert.deepEqual(saved.state.presetOverride, preset('本对话提示词'));
  saved = await call('/native-selection', { id: 'next', selection: { cardId: 'card' } });
  assert.equal(saved.state.userName, '新对话访客'); assert.equal(saved.state.config.historyTurns, 9);
  assert.deepEqual(saved.state.presetOverride, preset('全局默认提示词'));
  await call('/item', { sessionId: 'first', id: 'preset', data: preset('本对话第二版') });
  assert.deepEqual((await store.session('next')).presetOverride, preset('全局默认提示词'));
  assert.deepEqual((await store.item('preset')).data, preset('本对话第二版'));
  const patch = { local: [{ key: 'bubble-style', value: 'session-only' }], databases: [] };
  await call('/runtime', { sessionId: 'first', method: 'storage', args: patch });
  assert.equal((await call('/native-state?id=first')).runtimeStorage.local['bubble-style'], 'session-only');
  assert.equal((await call('/native-state?id=next')).runtimeStorage.local?.['bubble-style'], undefined);
  const before = await store.session('first');
  const renamed = await call('/runtime', { sessionId: 'first', method: 'userName', args: { userName: '  台词框名字  ' } });
  assert.equal(renamed.state.userName, '台词框名字');
  assert.equal((await call('/native-state?id=first')).state.userName, '台词框名字');
  assert.deepEqual(renamed.state.messages, before.messages);
  assert.equal((await store.session('next')).userName, '新对话访客');
  assert.equal((await store.settings()).selection.userName, '新对话访客');
});

test('Configuration history only records explicit saves and excludes story state', async t => {
  const root = await mkdtemp(join(tmpdir(), 'tavern-configuration-history-'));
  t.after(()=>rm(root,{recursive:true,force:true}));
  const store = new Store(root); await store.init();
  await store.putItem({id:'preset',kind:'preset',name:'写作',data:{}});
  const {configurationHistory,saveConfiguration}=await import('../src/configuration-history.js');
  assert.deepEqual(await configurationHistory(store),[]);
  await store.saveSession({id:'chat',characters:[],memories:{},messages:[{id:'story',content:'剧情内容'}],cardId:'card',presetId:'preset',config:defaultConfig(),presetOverride:{prompts:['第一版']},variables:{secret:'剧情'}});
  assert.deepEqual(await configurationHistory(store),[]);
  await saveConfiguration(store,{selection:{cardId:'card',presetId:'preset'},configuration:{presetOverride:{prompts:['第一版']},config:defaultConfig()}});
  await saveConfiguration(store,{selection:{cardId:'card',presetId:'preset'},configuration:{presetOverride:{prompts:['第二版']},config:defaultConfig()}});
  const profiles=await configurationHistory(store);
  assert.equal(profiles.length,2);assert.deepEqual(profiles.map(p=>p.configuration.presetOverride.prompts[0]),['第二版','第一版']);
  assert.ok(profiles.every(p=>!JSON.stringify(p).includes('剧情')));
  assert.deepEqual(profiles[1].selection.worldbookIds,[]);assert.deepEqual(profiles[1].configuration.regexOrder,[0,2,1]);
});
